language: python
python:
    - "2.5"
    - "2.6"
    - "2.7"
env:
    - DJANGO_VERSION=1.2
    - DJANGO_VERSION=1.3
    - DJANGO_VERSION=1.4
install: pip install Django==$DJANGO_VERSION django-markupfield markdown docutils --use-mirrors
script: django-admin.py test --settings=example.settings --pythonpath=. markupwiki
notifications:
    email:
        - james.p.turk@gmail.com
