language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
env:
    - DJANGO_PACKAGE="Django<1.5"
    - DJANGO_PACKAGE="Django>=1.5,<1.6"
    - DJANGO_PACKAGE="Django>=1.6,<1.7"
install: pip install $DJANGO_PACKAGE markdown docutils --use-mirrors
script: django-admin.py test --settings=example.settings --pythonpath=.
matrix:
    exclude:
        - python: "3.3"
          env: DJANGO_PACKAGE="Django<1.5"
notifications:
    email:
        - james.p.turk@gmail.com
